config/routes.rb
Rails.application.routes.draw do
  root to: "searches#new"
  resources :searches, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_and_belongs_to_many :search
  belongs_to :category
end

app/models/search.rb
class Search < ApplicationRecord
  has_and_belongs_to_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    interactor = Searches::NewInteractor.new(self)
    interactor.call
    @presenter = interactor.build_presenter
  end

  def create
    interactor = Searches::CreateInteractor.new(self)
    interactor.call
    @presenter = interactor.build_presenter
    if interactor.success
      redirect_to interactor.search
    end
  end

  def show
    interactor = Searches::ShowInteractor.new(self)
    interactor.call
    @presenter = interactor.build_presenter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChuckNorrisFacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_quote.html.slim
ul
  li = image_tag(quote["image_url"])
  li = quote["body"]
  li = quote["category"]
  li = link_to(t("searches.link"), quote["url"])

app/views/searches/new.html.slim
h1 
  = t("searches.welcome")

  = form_tag('/searches') do
    = text_field_tag 'query', '', size: 75
    = submit_tag "Find!", data: { disable_with: "Searching..." }
  - @presenter[:categories].each do |category|
    = button_to(t("categories.#{category}"), searches_path + "?category=#{category}")
  
  = button_to("Random!", searches_path + "?option=random")

app/views/searches/show.html.slim
h1 
  = t("searches.title")

- if @presenter[:quotes].present?
  - @presenter[:quotes].each do |quote|
    = render("quote", quote: quote)
- else
  h3 = t("quotes.no_cuotes")